# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""'pyfly db' commands for Alembic migration management."""

from __future__ import annotations

import functools
from collections.abc import Callable
from pathlib import Path
from typing import Any

import click

from pyfly.cli.console import console
from pyfly.data.relational.migrations import MigrationError

_ENV_PY_TEMPLATE = '''\
"""Alembic environment of a PyFly application (generated by ``pyfly db init``).

``pyfly db`` and the startup migrations (pyfly.data.relational.migrations.enabled) run it on the
application's primary datasource: pyfly.data.relational.url from pyfly.yaml (with the active profiles and
the environment), or sqlalchemy.url from alembic.ini when pyfly.yaml configures none.
"""

import asyncio
from logging.config import fileConfig

from alembic import context

from pyfly.data.relational.migrations import (
    migration_connection,
    migration_metadata,
    migration_url,
    refuse_destructive_autogenerate,
)
from pyfly.data.relational.sqlalchemy.types import render_item

config = context.config

# From the command line, alembic.ini configures Alembic's loggers and leaves every other logger alone. The
# startup migrations keep the application's logging: the runner sets configure_logger to False.
if config.config_file_name is not None and config.attributes.get("configure_logger", True):
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# The modules that declare the application's entities, used when pyfly.data.relational.migrations.models
# lists none (a package is imported with every module under it, except the application's entry point).
MODEL_PACKAGES: list[str] = []

# The application's entity models and the framework's own tables (pyfly_*): autogenerate compares the
# database with both, and never proposes dropping either.
target_metadata = migration_metadata(config, default_models=MODEL_PACKAGES)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    context.configure(
        url=migration_url(config),
        target_metadata=target_metadata,
        literal_binds=True,
        render_as_batch=True,  # Required for SQLite ALTER TABLE support
        render_item=render_item,  # Imports the module of PyFly column types (UtcDateTime) in revisions
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection):
    """Helper executed inside an async connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=True,  # Required for SQLite ALTER TABLE support
        render_item=render_item,  # Imports the module of PyFly column types (UtcDateTime) in revisions
        process_revision_directives=refuse_destructive_autogenerate,  # No revision that drops every table
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations on the application's database, in one transaction, under the schema lock."""
    async with migration_connection(config) as connection:
        await connection.run_sync(do_run_migrations)


def run_migrations_online() -> None:
    """Run migrations in 'online' mode: on the connection the startup migrations hand over, or a new one."""
    connection = config.attributes.get("connection")
    if connection is None:
        asyncio.run(run_async_migrations())
    else:
        do_run_migrations(connection)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''

_MODEL_PACKAGES_LINE = "MODEL_PACKAGES: list[str] = []\n"


def render_env_py(model_packages: list[str]) -> str:
    """The ``env.py`` of ``pyfly db init``, importing *model_packages* when the configuration names no models."""
    listed = ", ".join(repr(name) for name in model_packages)
    return _ENV_PY_TEMPLATE.replace(_MODEL_PACKAGES_LINE, f"MODEL_PACKAGES: list[str] = [{listed}]\n")


def _project_packages() -> list[str]:
    """The package of the project in the working directory (``pyfly.app.module``, or ``src/<package>``)."""
    from pyfly.cli._project import ProjectNotFoundError, detect_project

    try:
        return [detect_project(Path.cwd()).package]
    except ProjectNotFoundError:
        return []


def _require_alembic() -> tuple[Any, type]:
    """Import alembic lazily, failing with a helpful message if not installed."""
    try:
        from alembic import command  # noqa: N812
        from alembic.config import Config  # noqa: N812
    except ImportError:
        console.print("[error]\u2717 alembic is not installed.[/error]")
        console.print("[dim]Install the data-relational extra: pyfly[data-relational][/dim]")
        raise SystemExit(1) from None
    return command, Config


def _get_alembic_config() -> Any:
    """Load Alembic config from the current directory.

    Raises :class:`SystemExit` when ``alembic.ini`` is missing.
    """
    _, config_cls = _require_alembic()
    ini_path = Path("alembic.ini")
    if not ini_path.exists():
        console.print("[error]\u2717[/error] alembic.ini not found. Run 'pyfly db init' first.")
        raise SystemExit(1)
    return config_cls(str(ini_path))


def _reports_migration_errors(function: Callable[..., None]) -> Callable[..., None]:
    """Print a :class:`~pyfly.data.relational.migrations.MigrationError` (no database, no models, a constraint
    a rebuild would lose) as a one-line error and exit with status 1, instead of a traceback."""

    @functools.wraps(function)
    def wrapper(*args: Any, **kwargs: Any) -> None:
        try:
            function(*args, **kwargs)
        except MigrationError as error:
            console.print(f"[error]\u2717[/error] {error}")
            raise SystemExit(1) from None

    return wrapper


@click.group()
def db_group() -> None:
    """Database migration commands (powered by Alembic)."""


@db_group.command("init")
def init_cmd() -> None:
    """Initialize the Alembic migration environment."""
    command, config_cls = _require_alembic()

    directory = "alembic"
    if Path(directory).exists():
        console.print(
            f"[error]\u2717[/error] Directory '{directory}' already exists. "
            "Remove it first if you want to re-initialize."
        )
        raise SystemExit(1)

    cfg = config_cls("alembic.ini")
    command.init(cfg, directory)

    # Overwrite the generated env.py with the PyFly-customized template.
    packages = _project_packages()
    env_py_path = Path(directory) / "env.py"
    env_py_path.write_text(render_env_py(packages))

    console.print("[success]\u2713[/success] Initialized Alembic migration environment in 'alembic/'.")
    if packages:
        modules = ", ".join(packages)
        console.print(f"[dim]Models: every module of {modules} (pyfly.data.relational.migrations.models)[/dim]")
    else:
        console.print(
            "[dim]List the modules that declare your entities in pyfly.data.relational.migrations.models[/dim]"
        )


@db_group.command("migrate")
@click.option(
    "--message",
    "-m",
    default=None,
    help="Revision message.",
)
@_reports_migration_errors
def migrate_cmd(message: str | None) -> None:
    """Auto-generate a new migration revision."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.revision(cfg, message=message, autogenerate=True)
    console.print("[success]\u2713[/success] Migration revision created.")


@db_group.command("upgrade")
@click.argument("revision", default="head")
@_reports_migration_errors
def upgrade_cmd(revision: str) -> None:
    """Upgrade the database to a given revision (default: head)."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.upgrade(cfg, revision)
    console.print(f"[success]\u2713[/success] Database upgraded to {revision}.")


@db_group.command("downgrade")
@click.argument("revision")
@_reports_migration_errors
def downgrade_cmd(revision: str) -> None:
    """Downgrade the database to a given revision."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.downgrade(cfg, revision)
    console.print(f"[success]\u2713[/success] Database downgraded to {revision}.")


@db_group.command("current")
@click.option("--verbose", "-v", is_flag=True, help="Show full revision details.")
@_reports_migration_errors
def current_cmd(verbose: bool) -> None:
    """Show the current database revision."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.current(cfg, verbose=verbose)


@db_group.command("history")
@click.option("--verbose", "-v", is_flag=True, help="Show full revision details.")
def history_cmd(verbose: bool) -> None:
    """List the migration history."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.history(cfg, verbose=verbose)


@db_group.command("heads")
@click.option("--verbose", "-v", is_flag=True, help="Show full revision details.")
def heads_cmd(verbose: bool) -> None:
    """Show the current head revision(s)."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.heads(cfg, verbose=verbose)


@db_group.command("show")
@click.argument("revision")
def show_cmd(revision: str) -> None:
    """Show details of a specific revision."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.show(cfg, revision)


@db_group.command("revision")
@click.option("--message", "-m", default=None, help="Revision message.")
@click.option("--autogenerate", is_flag=True, help="Diff models to populate the revision (like 'migrate').")
@_reports_migration_errors
def revision_cmd(message: str | None, autogenerate: bool) -> None:
    """Create a new revision (empty by default; --autogenerate to diff models)."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.revision(cfg, message=message, autogenerate=autogenerate)
    console.print("[success]\u2713[/success] Revision created.")


@db_group.command("stamp")
@click.argument("revision")
@_reports_migration_errors
def stamp_cmd(revision: str) -> None:
    """Stamp the database with a revision without running migrations."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.stamp(cfg, revision)
    console.print(f"[success]\u2713[/success] Database stamped to {revision}.")


@db_group.command("merge")
@click.argument("revisions", nargs=-1, required=True)
@click.option("--message", "-m", default=None, help="Merge revision message.")
def merge_cmd(revisions: tuple[str, ...], message: str | None) -> None:
    """Merge multiple head revisions into one."""
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.merge(cfg, list(revisions), message=message)
    console.print("[success]\u2713[/success] Revisions merged.")


@db_group.command("reset")
@click.option("--yes", is_flag=True, help="Skip the confirmation prompt.")
@_reports_migration_errors
def reset_cmd(yes: bool) -> None:
    """Downgrade to base then upgrade to head (DESTRUCTIVE)."""
    if not yes:
        click.confirm("This downgrades to base and re-applies all migrations. Continue?", abort=True)
    command, _ = _require_alembic()
    cfg = _get_alembic_config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    console.print("[success]\u2713[/success] Database reset to head.")
