# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""SqlAlchemyFlagStore on the shared tables (spec 4.6), on every lane of the backend matrix.

The default run covers the sqlite-file lane; `pytest -m "integration and pg"` (mysql, mariadb) runs the servers.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from datetime import UTC, datetime

import pytest
from sqlalchemy import event, text
from sqlalchemy.dialects import mysql, postgresql, sqlite
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.schema import CreateIndex, CreateTable

from pyfly.data.relational.framework_schema import (
    FEATURE_FLAG_CHANGES,
    FEATURE_FLAGS,
    FrameworkSchemaError,
    ZonelessUtcTimestamp,
    feature_flag_changes,
    feature_flag_changes_table,
    feature_flags,
    framework_metadata,
)
from pyfly.data.transaction import infrastructure_unit
from pyfly.feature_flags.store.ports import FlagConflictError
from pyfly.feature_flags.store.sqlalchemy import SqlAlchemyFlagStore
from tests.feature_flags.store_contract import FlagStoreContract
from tests.feature_flags.support import bool_flag
from tests.support.backend_matrix import RelationalBackend


class TestSqlAlchemyFlagStore(FlagStoreContract):
    @pytest.fixture
    async def store(self, relational_backend: RelationalBackend) -> AsyncIterator[SqlAlchemyFlagStore]:
        engine = relational_backend.create_engine()
        store = SqlAlchemyFlagStore(engine)
        await store.start()
        yield store
        await store.stop()


def test_the_tables_are_declared_on_the_framework_metadata_with_the_shared_names() -> None:
    assert (FEATURE_FLAGS, FEATURE_FLAG_CHANGES) == ("firefly_feature_flags", "firefly_feature_flag_changes")
    assert framework_metadata.tables[FEATURE_FLAGS] is feature_flags
    assert [column.name for column in feature_flags.columns] == [
        "flag_key",
        "definition",
        "version",
        "updated_at",
        "updated_by",
    ]
    assert [column.name for column in feature_flag_changes.columns] == [
        "id",
        "flag_key",
        "action",
        "definition",
        "previous",
        "actor",
        "changed_at",
    ]
    [index] = feature_flag_changes.indexes
    assert index.name == "firefly_feature_flag_changes_key" and [c.name for c in index.columns] == ["flag_key", "id"]
    assert isinstance(feature_flags.c.updated_at.type, ZonelessUtcTimestamp)


def test_the_ddl_matches_the_contract_on_each_backend() -> None:
    pg = str(CreateTable(feature_flag_changes).compile(dialect=postgresql.dialect()))
    assert (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY" in pg and "changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL" in pg
    )
    my = str(CreateTable(feature_flags).compile(dialect=mysql.dialect()))
    assert "flag_key VARCHAR(128)" in my and "updated_at DATETIME(6) NOT NULL" in my
    lite = str(CreateIndex(next(iter(feature_flag_changes.indexes))).compile(dialect=sqlite.dialect()))
    assert lite == "CREATE INDEX firefly_feature_flag_changes_key ON firefly_feature_flag_changes (flag_key, id)"


def test_a_custom_changes_table_gets_an_index_of_its_own() -> None:
    custom = feature_flag_changes_table("ff_custom_changes")
    try:
        assert [index.name for index in custom.indexes] == ["ff_custom_changes_key"]
    finally:
        framework_metadata.remove(custom)


async def test_missing_tables_fail_fast_when_the_store_may_not_create_them(
    relational_backend: RelationalBackend,
) -> None:
    store = SqlAlchemyFlagStore(relational_backend.create_engine(), create_tables=False)
    with pytest.raises(FrameworkSchemaError, match="firefly_feature_flags"):
        await store.start()


# LaraFly FeatureFlagSchema.php at 0e3dad5: binary keys, unbounded JSON and zoneless UTC microseconds.
LARAFLY_SCHEMA: dict[str, list[str]] = {
    "sqlite": [
        "CREATE TABLE firefly_feature_flags (flag_key varchar NOT NULL PRIMARY KEY, definition text NOT NULL, "
        "version integer NOT NULL, updated_at datetime NOT NULL, updated_by varchar NULL)",
        "CREATE TABLE firefly_feature_flag_changes (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, "
        "flag_key varchar NOT NULL, action varchar NOT NULL, definition text NULL, previous text NULL, "
        "actor varchar NULL, changed_at datetime NOT NULL)",
    ],
    "postgresql": [
        "CREATE TABLE firefly_feature_flags (flag_key varchar(128) NOT NULL PRIMARY KEY, definition text NOT NULL, "
        "version integer NOT NULL, updated_at timestamp(6) without time zone NOT NULL, updated_by varchar(255) NULL)",
        "CREATE TABLE firefly_feature_flag_changes (id bigserial PRIMARY KEY, flag_key varchar(128) NOT NULL, "
        "action varchar(16) NOT NULL, definition text NULL, previous text NULL, actor varchar(255) NULL, "
        "changed_at timestamp(6) without time zone NOT NULL)",
    ],
    "mysql": [
        "CREATE TABLE firefly_feature_flags (flag_key varchar(128) CHARACTER SET utf8mb4 "
        "COLLATE {collation} NOT NULL PRIMARY KEY, definition longtext NOT NULL, "
        "version int NOT NULL, updated_at datetime(6) NOT NULL, updated_by varchar(255) NULL) DEFAULT CHARSET utf8mb4",
        "CREATE TABLE firefly_feature_flag_changes (id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY, "
        "flag_key varchar(128) CHARACTER SET utf8mb4 COLLATE {collation} NOT NULL, action varchar(16) NOT NULL, "
        "definition longtext NULL, previous longtext NULL, actor varchar(255) NULL, changed_at datetime(6) "
        "NOT NULL) DEFAULT CHARSET utf8mb4",
    ],
}
LARAFLY_INDEX = "CREATE INDEX firefly_feature_flag_changes_key ON firefly_feature_flag_changes (flag_key, id)"
PHP_DEFINITION = (
    '{"state":"ENABLED","variants":{"on":true,"off":false},"defaultVariant":"on","metadata":{"owner":"php"}}'
)
PHP_LARGE_DEFINITION = json.dumps({"state": "ENABLED", "variants": {"text": "x" * 80_000}, "defaultVariant": "text"})


async def test_tables_created_by_larafly_are_read_and_written(relational_backend: RelationalBackend) -> None:
    """Review focus 3: a service on a database LaraFly migrated (shared control plane) must boot, read and write."""
    engine = relational_backend.create_engine()
    dialect = "mysql" if relational_backend.dialect in ("mysql", "mariadb") else relational_backend.dialect
    collation = "utf8mb4_nopad_bin" if relational_backend.dialect == "mariadb" else "utf8mb4_0900_bin"
    async with engine.begin() as connection:
        for statement in [*LARAFLY_SCHEMA[dialect], LARAFLY_INDEX]:
            await connection.execute(text(statement.format(collation=collation)))
        await connection.execute(
            text(
                "INSERT INTO firefly_feature_flags (flag_key, definition, version, updated_at, updated_by) "
                "VALUES ('php-flag', :definition, 3, '2026-10-01 09:30:00.123456', 'ops@example.com')"
            ),
            {"definition": PHP_DEFINITION},
        )
        await connection.execute(
            text(
                "INSERT INTO firefly_feature_flags (flag_key, definition, version, updated_at, updated_by) "
                "VALUES ('PHP-FLAG', :definition, 1, '2026-10-01 09:30:00.654321', NULL)"
            ),
            {"definition": PHP_LARGE_DEFINITION},
        )
        await connection.execute(
            text(
                "INSERT INTO firefly_feature_flag_changes (flag_key, action, definition, previous, actor, changed_at) "
                "VALUES ('php-flag', 'put', :definition, NULL, 'ops@example.com', '2026-10-01 09:30:00.123456')"
            ),
            {"definition": PHP_DEFINITION},
        )
    if dialect != "sqlite":
        async with engine.connect() as connection:
            if dialect == "postgresql":
                await connection.execute(text("SET TIME ZONE '+08:00'"))
            else:
                await connection.execute(text("SET time_zone = '+08:00'"))
            try:
                raw = await connection.execute(
                    text("SELECT updated_at FROM firefly_feature_flags WHERE flag_key = 'php-flag'")
                )
                assert raw.scalar_one() == datetime(2026, 10, 1, 9, 30, 0, 123456)
            finally:
                if dialect == "postgresql":
                    await connection.execute(text("SET TIME ZONE 'UTC'"))
                else:
                    await connection.execute(text("SET time_zone = '+00:00'"))
    store = SqlAlchemyFlagStore(engine, create_tables=False)
    await store.start()  # ensure_tables accepts LaraFly's columns (no TIMESTAMP WITH TIME ZONE demanded)
    stored = await store.get("php-flag")
    assert stored is not None
    assert stored.definition == json.loads(PHP_DEFINITION) and stored.version == 3
    assert stored.updated_at == datetime(2026, 10, 1, 9, 30, 0, 123456, tzinfo=UTC)
    assert stored.updated_by == "ops@example.com"
    upper = await store.get("PHP-FLAG")
    assert upper is not None and upper.definition == json.loads(PHP_LARGE_DEFINITION)
    assert upper.updated_at == datetime(2026, 10, 1, 9, 30, 0, 654321, tzinfo=UTC)
    assert (await store.get("Php-Flag")) is None
    revision = await store.revision()
    assert revision >= 1
    change = await store.put("php-flag", bool_flag("off"), actor="pyfly", expected_version=3)
    assert change.id > revision and change.previous == json.loads(PHP_DEFINITION)
    assert [(c.actor, c.action) for c in await store.history("php-flag")] == [
        ("pyfly", "put"),
        ("ops@example.com", "put"),
    ]
    assert (await store.get("php-flag")).version == 4  # type: ignore[union-attr]
    await store.stop()


async def test_failed_audit_insert_rolls_back_the_flag_row_and_revision(
    relational_backend: RelationalBackend,
) -> None:
    engine = relational_backend.create_engine()
    store = SqlAlchemyFlagStore(engine)
    await store.start()
    await store.put("a", bool_flag("on"), actor="first")
    row_before = await store.get("a")
    history_before = await store.history("a")
    revision_before = await store.revision()
    updated = False

    def after_execute(
        connection: object, cursor: object, statement: str, parameters: object, context: object, executemany: bool
    ) -> None:
        nonlocal updated
        if statement.lstrip().upper().startswith("UPDATE FIREFLY_FEATURE_FLAGS"):
            updated = True

    def fail_audit(
        connection: object, cursor: object, statement: str, parameters: object, context: object, executemany: bool
    ) -> None:
        if statement.lstrip().upper().startswith("INSERT INTO FIREFLY_FEATURE_FLAG_CHANGES"):
            assert updated
            raise RuntimeError("injected audit failure")

    event.listen(engine.sync_engine, "after_cursor_execute", after_execute)
    event.listen(engine.sync_engine, "before_cursor_execute", fail_audit)
    try:
        with pytest.raises(RuntimeError, match="injected audit failure"):
            await store.put("a", bool_flag("off"), actor="second")
    finally:
        event.remove(engine.sync_engine, "after_cursor_execute", after_execute)
        event.remove(engine.sync_engine, "before_cursor_execute", fail_audit)

    assert updated
    assert await store.get("a") == row_before
    assert await store.history("a") == history_before
    assert await store.revision() == revision_before
    await store.stop()


@pytest.mark.parametrize("action", ["put", "delete"])
async def test_caught_audit_failure_rolls_back_only_its_write_in_a_caller_unit(
    relational_backend: RelationalBackend, action: str
) -> None:
    engine = relational_backend.create_engine()
    store = SqlAlchemyFlagStore(engine)
    await store.start()
    await store.put("a", bool_flag("on"), actor="first")
    row_before = await store.get("a")
    history_before = await store.history("a")
    revision_before = await store.revision()
    mutated = False

    def after_execute(
        connection: object, cursor: object, statement: str, parameters: object, context: object, executemany: bool
    ) -> None:
        nonlocal mutated
        prefix = "UPDATE" if action == "put" else "DELETE FROM"
        if statement.lstrip().upper().startswith(f"{prefix} FIREFLY_FEATURE_FLAGS"):
            mutated = True

    def fail_audit(
        connection: object, cursor: object, statement: str, parameters: object, context: object, executemany: bool
    ) -> None:
        if statement.lstrip().upper().startswith("INSERT INTO FIREFLY_FEATURE_FLAG_CHANGES"):
            assert mutated
            raise RuntimeError("injected audit failure")

    async with infrastructure_unit(engine):
        await store.put("unrelated-before", bool_flag(), actor="outer")
        event.listen(engine.sync_engine, "after_cursor_execute", after_execute)
        event.listen(engine.sync_engine, "before_cursor_execute", fail_audit)
        try:
            with pytest.raises(RuntimeError, match="injected audit failure"):
                if action == "put":
                    await store.put("a", bool_flag("off"), actor="second")
                else:
                    await store.delete("a", actor="second")
        finally:
            event.remove(engine.sync_engine, "after_cursor_execute", after_execute)
            event.remove(engine.sync_engine, "before_cursor_execute", fail_audit)
        assert mutated
        await store.put("unrelated-after", bool_flag(), actor="outer")

    assert await store.get("a") == row_before
    assert await store.history("a") == history_before
    assert await store.revision() == revision_before + 2
    assert await store.get("unrelated-before") is not None
    assert await store.get("unrelated-after") is not None
    await store.stop()


async def test_successful_write_joins_a_caller_unit_that_later_rolls_back(
    relational_backend: RelationalBackend,
) -> None:
    engine = relational_backend.create_engine()
    store = SqlAlchemyFlagStore(engine)
    await store.start()
    with pytest.raises(RuntimeError, match="outer failure"):
        async with infrastructure_unit(engine):
            await store.put("a", bool_flag(), actor="outer")
            raise RuntimeError("outer failure")

    assert await store.get("a") is None
    assert await store.history("a") == []
    assert await store.revision() == 0
    await store.stop()


@pytest.mark.backends("pg", "mysql", "mariadb")
@pytest.mark.parametrize(("seed", "expected_version"), [(True, 1), (True, None), (False, 0), (False, None)])
async def test_two_writers_keep_versions_and_history_consistent(
    relational_backend: RelationalBackend, seed: bool, expected_version: int | None, monkeypatch: pytest.MonkeyPatch
) -> None:
    engine = relational_backend.create_engine()
    store = SqlAlchemyFlagStore(engine)
    await store.start()
    if seed:
        await store.put("a", bool_flag("on"), actor="first")
    original_execute = AsyncSession.execute
    both_read = asyncio.Event()
    readers = 0

    async def synchronize_reads(self: AsyncSession, statement: object, *args: object, **kwargs: object) -> object:
        nonlocal readers
        result = await original_execute(self, statement, *args, **kwargs)
        if getattr(statement, "is_select", False) and store.tables[0] in statement.get_final_froms() and readers < 2:
            readers += 1
            if readers == 2:
                both_read.set()
            await asyncio.wait_for(both_read.wait(), timeout=5)
        return result

    monkeypatch.setattr(AsyncSession, "execute", synchronize_reads)
    results = await asyncio.gather(
        store.put("a", bool_flag("on"), actor="writer-one", expected_version=expected_version),
        store.put("a", bool_flag("off"), actor="writer-two", expected_version=expected_version),
        return_exceptions=True,
    )
    monkeypatch.setattr(AsyncSession, "execute", original_execute)

    assert readers == 2
    winners = [result for result in results if not isinstance(result, BaseException)]
    conflicts = [result for result in results if isinstance(result, FlagConflictError)]
    assert len(winners) == (1 if expected_version is not None else 2), results
    assert len(conflicts) == (1 if expected_version is not None else 0), results
    assert len([result for result in results if isinstance(result, BaseException)]) == len(conflicts), results
    row = await store.get("a")
    assert row is not None and row.version == int(seed) + len(winners)
    history = await store.history("a")
    assert len(history) == int(seed) + len(winners)
    assert await store.revision() == history[0].id
    assert {change.actor for change in history} == ({"first"} if seed else set()) | {winner.actor for winner in winners}
    assert history[-1].previous is None
    if seed:
        assert history[-1].definition == bool_flag("on")
    if len(winners) == 2:
        assert history[0].previous == history[1].definition
    elif seed:
        assert history[0].previous == bool_flag("on")
    else:
        assert history[0].previous is None
    await store.stop()
