# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""SqlAlchemyFlagStore on the shared tables (spec 4.6), on every lane of the backend matrix.

The default run covers the sqlite-file lane; `pytest -m "integration and pg"` (mysql, mariadb) runs the servers.
"""

from __future__ import annotations

import json
from collections.abc import AsyncIterator
from datetime import UTC, datetime

import pytest
from sqlalchemy import event, text
from sqlalchemy.dialects import mysql, postgresql, sqlite
from sqlalchemy.schema import CreateIndex, CreateTable

from pyfly.data.relational.framework_schema import (
    FEATURE_FLAG_CHANGES,
    FEATURE_FLAGS,
    FrameworkSchemaError,
    ZonelessUtcTimestamp,
    feature_flag_changes,
    feature_flag_changes_table,
    feature_flags,
    framework_metadata,
)
from pyfly.feature_flags.store.sqlalchemy import SqlAlchemyFlagStore
from tests.feature_flags.store_contract import FlagStoreContract
from tests.feature_flags.support import bool_flag
from tests.support.backend_matrix import RelationalBackend


class TestSqlAlchemyFlagStore(FlagStoreContract):
    @pytest.fixture
    async def store(self, relational_backend: RelationalBackend) -> AsyncIterator[SqlAlchemyFlagStore]:
        engine = relational_backend.create_engine()
        store = SqlAlchemyFlagStore(engine)
        await store.start()
        yield store
        await store.stop()


def test_the_tables_are_declared_on_the_framework_metadata_with_the_shared_names() -> None:
    assert (FEATURE_FLAGS, FEATURE_FLAG_CHANGES) == ("firefly_feature_flags", "firefly_feature_flag_changes")
    assert framework_metadata.tables[FEATURE_FLAGS] is feature_flags
    assert [column.name for column in feature_flags.columns] == [
        "flag_key",
        "definition",
        "version",
        "updated_at",
        "updated_by",
    ]
    assert [column.name for column in feature_flag_changes.columns] == [
        "id",
        "flag_key",
        "action",
        "definition",
        "previous",
        "actor",
        "changed_at",
    ]
    [index] = feature_flag_changes.indexes
    assert index.name == "firefly_feature_flag_changes_key" and [c.name for c in index.columns] == ["flag_key", "id"]
    assert isinstance(feature_flags.c.updated_at.type, ZonelessUtcTimestamp)


def test_the_ddl_matches_the_contract_on_each_backend() -> None:
    pg = str(CreateTable(feature_flag_changes).compile(dialect=postgresql.dialect()))
    assert (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY" in pg and "changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL" in pg
    )
    my = str(CreateTable(feature_flags).compile(dialect=mysql.dialect()))
    assert "flag_key VARCHAR(128)" in my and "updated_at DATETIME(6) NOT NULL" in my
    lite = str(CreateIndex(next(iter(feature_flag_changes.indexes))).compile(dialect=sqlite.dialect()))
    assert lite == "CREATE INDEX firefly_feature_flag_changes_key ON firefly_feature_flag_changes (flag_key, id)"


def test_a_custom_changes_table_gets_an_index_of_its_own() -> None:
    custom = feature_flag_changes_table("ff_custom_changes")
    try:
        assert [index.name for index in custom.indexes] == ["ff_custom_changes_key"]
    finally:
        framework_metadata.remove(custom)


async def test_missing_tables_fail_fast_when_the_store_may_not_create_them(
    relational_backend: RelationalBackend,
) -> None:
    store = SqlAlchemyFlagStore(relational_backend.create_engine(), create_tables=False)
    with pytest.raises(FrameworkSchemaError, match="firefly_feature_flags"):
        await store.start()


# Tables as LaraFly's migration creates them (Laravel schema builder: id() is a big auto-increment, timestamp() is a
# zone-less timestamp; SQLite stores datetime text without fractional seconds).
LARAFLY_DDL: dict[str, list[str]] = {
    "sqlite": [
        "CREATE TABLE firefly_feature_flags (flag_key varchar NOT NULL PRIMARY KEY, definition text NOT NULL, "
        "version integer NOT NULL, updated_at datetime NOT NULL, updated_by varchar NULL)",
        "CREATE TABLE firefly_feature_flag_changes (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, "
        "flag_key varchar NOT NULL, action varchar NOT NULL, definition text NULL, previous text NULL, "
        "actor varchar NULL, changed_at datetime NOT NULL)",
    ],
    "postgresql": [
        "CREATE TABLE firefly_feature_flags (flag_key varchar(128) NOT NULL PRIMARY KEY, definition text NOT NULL, "
        "version integer NOT NULL, updated_at timestamp(0) without time zone NOT NULL, updated_by varchar(255) NULL)",
        "CREATE TABLE firefly_feature_flag_changes (id bigserial PRIMARY KEY, flag_key varchar(128) NOT NULL, "
        "action varchar(16) NOT NULL, definition text NULL, previous text NULL, actor varchar(255) NULL, "
        "changed_at timestamp(0) without time zone NOT NULL)",
    ],
    "mysql": [
        "CREATE TABLE firefly_feature_flags (flag_key varchar(128) NOT NULL PRIMARY KEY, definition text NOT NULL, "
        "version int NOT NULL, updated_at timestamp NOT NULL, updated_by varchar(255) NULL) DEFAULT CHARSET utf8mb4",
        "CREATE TABLE firefly_feature_flag_changes (id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY, "
        "flag_key varchar(128) NOT NULL, action varchar(16) NOT NULL, definition text NULL, previous text NULL, "
        "actor varchar(255) NULL, changed_at timestamp NOT NULL) DEFAULT CHARSET utf8mb4",
    ],
}
LARAFLY_INDEX = "CREATE INDEX firefly_feature_flag_changes_key ON firefly_feature_flag_changes (flag_key, id)"
PHP_DEFINITION = (
    '{"state":"ENABLED","variants":{"on":true,"off":false},"defaultVariant":"on","metadata":{"owner":"php"}}'
)


async def test_tables_created_by_larafly_are_read_and_written(relational_backend: RelationalBackend) -> None:
    """Review focus 3: a service on a database LaraFly migrated (shared control plane) must boot, read and write."""
    engine = relational_backend.create_engine()
    dialect = "mysql" if relational_backend.dialect in ("mysql", "mariadb") else relational_backend.dialect
    async with engine.begin() as connection:
        for statement in [*LARAFLY_DDL[dialect], LARAFLY_INDEX]:
            await connection.execute(text(statement))
        await connection.execute(
            text(
                "INSERT INTO firefly_feature_flags (flag_key, definition, version, updated_at, updated_by) "
                "VALUES ('php-flag', :definition, 3, '2026-10-01 09:30:00', 'ops@example.com')"
            ),
            {"definition": PHP_DEFINITION},
        )
        await connection.execute(
            text(
                "INSERT INTO firefly_feature_flag_changes (flag_key, action, definition, previous, actor, changed_at) "
                "VALUES ('php-flag', 'put', :definition, NULL, 'ops@example.com', '2026-10-01 09:30:00')"
            ),
            {"definition": PHP_DEFINITION},
        )
    store = SqlAlchemyFlagStore(engine, create_tables=False)
    await store.start()  # ensure_tables accepts LaraFly's columns (no TIMESTAMP WITH TIME ZONE demanded)
    stored = await store.get("php-flag")
    assert stored is not None
    assert stored.definition == json.loads(PHP_DEFINITION) and stored.version == 3
    assert stored.updated_at == datetime(2026, 10, 1, 9, 30, tzinfo=UTC) and stored.updated_by == "ops@example.com"
    revision = await store.revision()
    assert revision >= 1
    change = await store.put("php-flag", bool_flag("off"), actor="pyfly", expected_version=3)
    assert change.id > revision and change.previous == json.loads(PHP_DEFINITION)
    assert [(c.actor, c.action) for c in await store.history("php-flag")] == [
        ("pyfly", "put"),
        ("ops@example.com", "put"),
    ]
    assert (await store.get("php-flag")).version == 4  # type: ignore[union-attr]
    await store.stop()


async def test_failed_audit_insert_rolls_back_the_flag_row_and_revision(
    relational_backend: RelationalBackend,
) -> None:
    engine = relational_backend.create_engine()
    store = SqlAlchemyFlagStore(engine)
    await store.start()
    await store.put("a", bool_flag("on"), actor="first")
    row_before = await store.get("a")
    history_before = await store.history("a")
    revision_before = await store.revision()
    updated = False

    def after_execute(
        connection: object, cursor: object, statement: str, parameters: object, context: object, executemany: bool
    ) -> None:
        nonlocal updated
        if statement.lstrip().upper().startswith("UPDATE FIREFLY_FEATURE_FLAGS"):
            updated = True

    def fail_audit(
        connection: object, cursor: object, statement: str, parameters: object, context: object, executemany: bool
    ) -> None:
        if statement.lstrip().upper().startswith("INSERT INTO FIREFLY_FEATURE_FLAG_CHANGES"):
            assert updated
            raise RuntimeError("injected audit failure")

    event.listen(engine.sync_engine, "after_cursor_execute", after_execute)
    event.listen(engine.sync_engine, "before_cursor_execute", fail_audit)
    try:
        with pytest.raises(RuntimeError, match="injected audit failure"):
            await store.put("a", bool_flag("off"), actor="second")
    finally:
        event.remove(engine.sync_engine, "after_cursor_execute", after_execute)
        event.remove(engine.sync_engine, "before_cursor_execute", fail_audit)

    assert updated
    assert await store.get("a") == row_before
    assert await store.history("a") == history_before
    assert await store.revision() == revision_before
    await store.stop()
