# Copyright 2026 Firefly Software Foundation.
# Licensed under the Apache License, Version 2.0.
"""IdpAdapter port — the contract every IDP implementation must satisfy."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from pyfly.idp.models import (
    AuthResult,
    IdpRole,
    IdpUser,
    LoginRequest,
    MfaChallenge,
    PasswordChangeRequest,
    SessionIntrospection,
)


@runtime_checkable
class IdpAdapter(Protocol):
    """Pluggable identity provider — bridge to Keycloak / Cognito / etc."""

    name: str

    # User management ------------------------------------------------------
    async def create_user(self, user: IdpUser, password: str) -> IdpUser: ...
    async def get_user(self, user_id: str) -> IdpUser | None: ...
    async def find_by_username(self, username: str) -> IdpUser | None: ...
    async def update_user(self, user: IdpUser) -> IdpUser: ...
    async def delete_user(self, user_id: str) -> bool: ...
    async def list_users(self, *, limit: int = 100) -> list[IdpUser]: ...

    # Authentication -------------------------------------------------------
    async def login(self, request: LoginRequest) -> AuthResult: ...
    async def logout(self, access_token: str) -> bool: ...
    async def refresh(self, refresh_token: str) -> AuthResult: ...
    async def introspect(self, access_token: str) -> SessionIntrospection: ...

    # Password / MFA -------------------------------------------------------
    async def change_password(self, request: PasswordChangeRequest) -> bool: ...
    async def reset_password(self, user_id: str) -> str: ...

    # MFA (Java parity) ----------------------------------------------------
    # DEFER: listSessions / revokeSession / createScope belong to the session
    # registry / authz server, not the IdpAdapter port.
    async def mfa_challenge(self, user_id: str) -> MfaChallenge: ...
    async def mfa_verify(self, challenge_id: str, code: str) -> AuthResult: ...

    # Extended user info (Java parity) -------------------------------------
    async def get_user_info(self, access_token: str) -> IdpUser | None: ...
    async def register_user(self, user: IdpUser, password: str) -> IdpUser: ...
    async def get_roles(self, user_id: str) -> list[IdpRole]: ...

    # Roles ----------------------------------------------------------------
    async def assign_role(self, user_id: str, role: str) -> bool: ...
    async def revoke_role(self, user_id: str, role: str) -> bool: ...
    async def list_roles(self) -> list[IdpRole]: ...
